version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pyro_api
      POSTGRES_PASSWORD: DkqGk5d3aXaQrdTRqnNFg4QJoAiWcb
      POSTGRES_DB: pyro_legacy
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pyro_network

  redis:
    image: redis:alpine
    command: redis-server --requirepass ""
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - pyro_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-redis_secure_password}
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin_password}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - pyro_network

networks:
  pyro_network:
    name: pyro_network
    driver: bridge
    attachable: true

volumes:
  db_data:
  redis_data: