import type { DashboardNavColor } from '@/types/settings';
import type { ColorScheme } from '@/styles/theme/types';

export const navColorStyles = {
	dark: {
		blend_in: {
			'--SideNav-background': 'rgba(10, 20, 30, 0.7)',
			'--SideNav-color': 'var(--mui-palette-common-white)',
			'--SideNav-border': '1px solid rgba(90, 220, 220, 0.3)',
			'--NavGroup-title-color': 'var(--mui-palette-primary-main)',
			'--NavItem-color': 'rgba(200, 240, 240, 0.9)',
			'--NavItem-hover-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.15)',
			'--NavItem-active-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.25)',
			'--NavItem-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
			'--NavItem-icon-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-600)',
			'--NavItem-expand-color': 'var(--mui-palette-primary-main)',
			'--NavItem-children-border': 'rgba(90, 220, 220, 0.3)',
			'--NavItem-children-indicator': 'var(--mui-palette-primary-main)',
			'--Workspaces-background': 'rgba(10, 15, 25, 0.8)',
			'--Workspaces-border-color': 'rgba(90, 220, 220, 0.3)',
			'--Workspaces-title-color': 'var(--mui-palette-primary-main)',
			'--Workspaces-name-color': 'rgba(200, 240, 240, 0.9)',
			'--Workspaces-expand-color': 'var(--mui-palette-primary-main)',
		},
		discrete: {
			'--SideNav-background': 'rgba(20, 30, 40, 0.8)',
			'--SideNav-color': 'var(--mui-palette-common-white)',
			'--SideNav-border': '1px solid rgba(90, 220, 220, 0.3)',
			'--NavGroup-title-color': 'var(--mui-palette-primary-main)',
			'--NavItem-color': 'rgba(200, 240, 240, 0.9)',
			'--NavItem-hover-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.15)',
			'--NavItem-active-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.25)',
			'--NavItem-active-color': 'var(--mui-palette-primary-main)', 
			'--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
			'--NavItem-icon-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-600)',
			'--NavItem-expand-color': 'var(--mui-palette-primary-main)',
			'--NavItem-children-border': 'rgba(90, 220, 220, 0.3)',
			'--NavItem-children-indicator': 'var(--mui-palette-primary-main)',
			'--Workspaces-background': 'rgba(10, 15, 25, 0.8)',
			'--Workspaces-border-color': 'rgba(90, 220, 220, 0.3)',
			'--Workspaces-title-color': 'var(--mui-palette-primary-main)',
			'--Workspaces-name-color': 'rgba(200, 240, 240, 0.9)',
			'--Workspaces-expand-color': 'var(--mui-palette-primary-main)',
		},
		evident: {
			'--SideNav-background': 'rgba(5, 10, 20, 0.9)',
			'--SideNav-color': 'var(--mui-palette-common-white)',
			'--SideNav-border': '1px solid rgba(90, 220, 220, 0.3)',
			'--NavGroup-title-color': 'var(--mui-palette-primary-main)',
			'--NavItem-color': 'rgba(200, 240, 240, 0.9)',
			'--NavItem-hover-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.15)',
			'--NavItem-active-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.25)', 
			'--NavItem-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
			'--NavItem-icon-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-600)',
			'--NavItem-expand-color': 'var(--mui-palette-primary-main)',
			'--NavItem-children-border': 'rgba(90, 220, 220, 0.3)',
			'--NavItem-children-indicator': 'var(--mui-palette-primary-main)',
			'--Workspaces-background': 'rgba(10, 15, 25, 0.8)',
			'--Workspaces-border-color': 'rgba(90, 220, 220, 0.3)',
			'--Workspaces-title-color': 'var(--mui-palette-primary-main)',
			'--Workspaces-name-color': 'rgba(200, 240, 240, 0.9)',
			'--Workspaces-expand-color': 'var(--mui-palette-primary-main)',
		},
	},
	light: {
		blend_in: {
			'--SideNav-background': 'rgba(250, 252, 255, 0.85)',
			'--SideNav-color': 'var(--mui-palette-text-primary)',
			'--SideNav-border': '1px solid rgba(90, 160, 255, 0.3)',
			'--NavGroup-title-color': 'var(--mui-palette-primary-main)',
			'--NavItem-color': 'var(--mui-palette-neutral-700)',
			'--NavItem-hover-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.08)',
			'--NavItem-active-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.15)',
			'--NavItem-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
			'--NavItem-icon-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-500)',
			'--NavItem-expand-color': 'var(--mui-palette-primary-main)',
			'--NavItem-children-border': 'rgba(90, 160, 255, 0.3)',
			'--NavItem-children-indicator': 'var(--mui-palette-primary-main)',
			'--Workspaces-background': 'rgba(245, 250, 255, 0.9)',
			'--Workspaces-border-color': 'rgba(90, 160, 255, 0.3)',
			'--Workspaces-title-color': 'var(--mui-palette-primary-main)',
			'--Workspaces-name-color': 'var(--mui-palette-neutral-800)',
			'--Workspaces-expand-color': 'var(--mui-palette-primary-main)',
		},
		discrete: {
			'--SideNav-background': 'rgba(240, 245, 255, 0.9)',
			'--SideNav-color': 'var(--mui-palette-text-primary)',
			'--SideNav-border': '1px solid rgba(90, 160, 255, 0.3)',
			'--NavGroup-title-color': 'var(--mui-palette-primary-main)',
			'--NavItem-color': 'var(--mui-palette-neutral-700)',
			'--NavItem-hover-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.08)',
			'--NavItem-active-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.15)',
			'--NavItem-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
			'--NavItem-icon-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-500)',
			'--NavItem-expand-color': 'var(--mui-palette-primary-main)',
			'--NavItem-children-border': 'rgba(90, 160, 255, 0.3)',
			'--NavItem-children-indicator': 'var(--mui-palette-primary-main)',
			'--Workspaces-background': 'rgba(245, 250, 255, 0.9)',
			'--Workspaces-border-color': 'rgba(90, 160, 255, 0.3)',
			'--Workspaces-title-color': 'var(--mui-palette-primary-main)',
			'--Workspaces-name-color': 'var(--mui-palette-neutral-800)',
			'--Workspaces-expand-color': 'var(--mui-palette-primary-main)',
		},
		evident: {
			'--SideNav-background': 'rgba(5, 10, 20, 0.9)',
			'--SideNav-color': 'var(--mui-palette-common-white)',
			'--SideNav-border': 'none',
			'--NavGroup-title-color': 'var(--mui-palette-primary-main)',
			'--NavItem-color': 'rgba(200, 240, 240, 0.9)',
			'--NavItem-hover-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.15)',
			'--NavItem-active-background': 'rgba(var(--mui-palette-primary-mainChannel), 0.25)',
			'--NavItem-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-disabled-color': 'var(--mui-palette-neutral-500)',
			'--NavItem-icon-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-active-color': 'var(--mui-palette-primary-main)',
			'--NavItem-icon-disabled-color': 'var(--mui-palette-neutral-600)',
			'--NavItem-expand-color': 'var(--mui-palette-primary-main)',
			'--NavItem-children-border': 'rgba(90, 220, 220, 0.3)',
			'--NavItem-children-indicator': 'var(--mui-palette-primary-main)',
			'--Workspaces-background': 'rgba(10, 15, 25, 0.8)',
			'--Workspaces-border-color': 'rgba(90, 220, 220, 0.3)',
			'--Workspaces-title-color': 'var(--mui-palette-primary-main)',
			'--Workspaces-name-color': 'rgba(200, 240, 240, 0.9)',
			'--Workspaces-expand-color': 'var(--mui-palette-primary-main)',
		},
	},
} satisfies Record<ColorScheme, Record<DashboardNavColor, Record<string, string>>>;
